version: '3.8'
services:
  web:
    build:
      context: ./
      target: runner
    volumes:
      - .:/app/
    command: npm run dev
    ports:
      - 9200:8080
    environment:
      NODE_ENV: development
